const ComptrollerErrorCodes = [
  "NO_ERROR",
  "UNAUTHORIZED",
  "COMPTROLLER_MISMATCH",
  "INSUFFICIENT_SHORTFALL",
  "INSUFFICIENT_LIQUIDITY",
  "INVALID_CLOSE_FACTOR",
  "INVALID_COLLATERAL_FACTOR",
  "INVALID_LIQUIDATION_INCENTIVE",
  "MARKET_NOT_ENTERED", // no longer possible
  "MARKET_NOT_LISTED",
  "MARKET_ALREADY_LISTED",
  "MATH_ERROR",
  "NONZERO_BORROW_BALANCE",
  "PRICE_ERROR",
  "REJECTION",
  "SNAPSHOT_ERROR",
  "TOO_MANY_ASSETS",
  "TOO_MUCH_REPAY",
  "INSUFFICIENT_BALANCE_FOR_VAI",
];

module.exports = { ComptrollerErrorCodes };
