#!/bin/bash

# SPDX-FileCopyrightText: 2020 Compound Labs, Inc.
# SPDX-License-Identifier: BSD-3-Clause

set -eo pipefail

DIR=`dirname $0`
PROJ_ROOT="$DIR/.."

"$PROJ_ROOT/node_modules/.bin/solium" -d "$PROJ_ROOT/tests"
"$PROJ_ROOT/node_modules/.bin/solium" -d "$PROJ_ROOT/contracts"
