import { Raw, VTokenConfig } from "./types";

export default [
  {
    name: "Venus USDC",
    symbol: "vUSDC",
    asset: "USDC",
    interestRateModel: {
      model: "two-kinks",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      baseRatePerYear2: "0",
      multiplierPerYear2: "0.7",
      kink2: "0.9",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.825",
      reserveFactor: "0.1",
      supplyCap: "258000000",
      borrowCap: "200000000",
    },
  },
  {
    name: "Venus USDT",
    symbol: "vUSDT",
    asset: "USDT",
    interestRateModel: {
      model: "two-kinks",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      baseRatePerYear2: "0",
      multiplierPerYear2: "0.7",
      kink2: "0.9",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.1",
      supplyCap: "600000000",
      borrowCap: "450000000",
    },
  },
  {
    name: "Venus BUSD",
    symbol: "vBUSD",
    asset: "BUSD",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0",
      multiplierPerYear: "0",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "1",
      supplyCap: "0",
      borrowCap: "0",
    },
  },
  {
    name: "Venus SXP",
    symbol: "vSXP",
    asset: "SXP",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.5",
      multiplierPerYear: "0.3",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "1",
      supplyCap: "0",
      borrowCap: "0",
    },
  },
  {
    name: "Venus XVS",
    symbol: "vXVS",
    asset: "XVS",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0",
      multiplierPerYear: "2.4",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.25",
      supplyCap: "1850000",
      borrowCap: "0",
    },
  },
  {
    name: "Venus BNB",
    symbol: "vBNB",
    asset: "BNB",
    interestRateModel: {
      model: "two-kinks",
      baseRatePerYear: "0",
      multiplierPerYear: "0.045",
      kink: "0.7",
      baseRatePerYear2: "0",
      multiplierPerYear2: "1.4",
      kink2: "0.8",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.78",
      reserveFactor: "0.3",
      supplyCap: "2672000",
      borrowCap: "2008000",
    },
  },
  {
    name: "Venus BTC",
    symbol: "vBTC",
    asset: "BTCB",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.025",
      multiplierPerYear: "0.09",
      kink: "0.9",
      jumpMultiplierPerYear: "2",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.2",
      supplyCap: "22770",
      borrowCap: "3531",
    },
  },
  {
    name: "Venus ETH",
    symbol: "vETH",
    asset: "ETH",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.03",
      kink: "0.9",
      jumpMultiplierPerYear: "4.5",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.2",
      supplyCap: "100000",
      borrowCap: "60000",
    },
  },
  {
    name: "Venus LTC",
    symbol: "vLTC",
    asset: "LTC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.12",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.63",
      reserveFactor: "0.2",
      supplyCap: "240000",
      borrowCap: "20000",
    },
  },
  {
    name: "Venus XRP",
    symbol: "vXRP",
    asset: "XRP",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.12",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.65",
      reserveFactor: "0.2",
      supplyCap: "24000000",
      borrowCap: "6000000",
    },
  },
  {
    name: "Venus BCH",
    symbol: "vBCH",
    asset: "BCH",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.2",
      supplyCap: "10000",
      borrowCap: "1000",
    },
  },
  {
    name: "Venus DOT",
    symbol: "vDOT",
    asset: "DOT",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.65",
      reserveFactor: "0.2",
      supplyCap: "1200000",
      borrowCap: "400000",
    },
  },
  {
    name: "Venus LINK",
    symbol: "vLINK",
    asset: "LINK",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.12",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.63",
      reserveFactor: "0.2",
      supplyCap: "900000",
      borrowCap: "80000",
    },
  },
  {
    name: "Venus DAI",
    symbol: "vDAI",
    asset: "DAI",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      jumpMultiplierPerYear: "2.5",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.1",
      supplyCap: "13910000",
      borrowCap: "7500000",
    },
  },
  {
    name: "Venus FIL",
    symbol: "vFIL",
    asset: "FIL",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.63",
      reserveFactor: "0.2",
      supplyCap: "1200000",
      borrowCap: "90000",
    },
  },
  {
    name: "Venus BETH",
    symbol: "vBETH",
    asset: "BETH",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.4",
      reserveFactor: "1",
      supplyCap: "0",
      borrowCap: "0.000000000000000001",
    },
  },
  {
    name: "Venus ADA",
    symbol: "vADA",
    asset: "ADA",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.63",
      reserveFactor: "0.2",
      supplyCap: "37510000",
      borrowCap: "2000000",
    },
  },
  {
    name: "Venus DOGE",
    symbol: "vDOGE",
    asset: "DOGE",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.43",
      reserveFactor: "0.2",
      supplyCap: "120000000",
      borrowCap: "4500000",
    },
  },
  {
    name: "Venus MATIC",
    symbol: "vMATIC",
    asset: "MATIC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.12",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.65",
      reserveFactor: "0.2",
      supplyCap: "5500000",
      borrowCap: "250000",
    },
  },
  {
    name: "Venus CAKE",
    symbol: "vCAKE",
    asset: "Cake",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0.25",
      supplyCap: "24000000",
      borrowCap: "3749000",
    },
  },
  {
    name: "Venus AAVE",
    symbol: "vAAVE",
    asset: "AAVE",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0.25",
      supplyCap: "20000",
      borrowCap: "3000",
    },
  },
  {
    name: "Venus TUSDOLD",
    symbol: "vTUSDOLD",
    asset: "TUSD",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0",
      multiplierPerYear: "0",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "1",
      supplyCap: "0",
      borrowCap: "0",
    },
  },
  {
    name: "Venus TRXOLD",
    symbol: "vTRXOLD",
    asset: "TRX",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "1",
      kink: "0.01",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "1",
      supplyCap: "0",
      borrowCap: "0",
    },
  },
  {
    name: "Venus TRX",
    symbol: "vTRX",
    asset: "TRX",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.525",
      reserveFactor: "0.25",
      supplyCap: "12000000",
      borrowCap: "6000000",
    },
  },
  {
    name: "Venus WBETH",
    symbol: "vWBETH",
    asset: "wBETH",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.75",
      jumpMultiplierPerYear: "2",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.2",
      supplyCap: "40000",
      borrowCap: "16000",
    },
  },
  {
    name: "Venus TUSD",
    symbol: "vTUSD",
    asset: "TUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      jumpMultiplierPerYear: "2.5",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.1",
      supplyCap: "750000",
      borrowCap: "600000",
    },
  },
  {
    name: "Venus UNI",
    symbol: "vUNI",
    asset: "UNI",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0.25",
      supplyCap: "2200000",
      borrowCap: "200000",
    },
  },
  {
    name: "Venus FDUSD",
    symbol: "vFDUSD",
    asset: "FDUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      jumpMultiplierPerYear: "5",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.1",
      supplyCap: "100000000",
      borrowCap: "80000000",
    },
    initialSupply: {
      amount: "9000",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus TWT",
    symbol: "vTWT",
    asset: "TWT",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.5",
      reserveFactor: "0.25",
      supplyCap: "4000000",
      borrowCap: "1000000",
    },
    initialSupply: {
      amount: "4401",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus SolvBTC",
    symbol: "vSolvBTC",
    asset: "SolvBTC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      kink: "0.5",
      jumpMultiplierPerYear: "2",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.2",
      supplyCap: "1720",
      borrowCap: "110",
    },
    initialSupply: {
      amount: "0.1572404",
      vTokenReceiver: "0xD5bAa0C3d61Ba3f4899565f269e5f9b186AAf14B",
    },
  },
  {
    name: "Venus THE",
    symbol: "vTHE",
    asset: "THE",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      kink: "0.45",
      jumpMultiplierPerYear: "3.5",
    },
    riskParameters: {
      collateralFactor: "0.53",
      reserveFactor: "0.25",
      supplyCap: "12000000",
      borrowCap: "6000000",
    },
    initialSupply: {
      amount: "12286",
      vTokenReceiver: "0x1c6C2498854662FDeadbC4F14eA2f30ca305104b",
    },
  },
  {
    name: "Venus SOL",
    symbol: "vSOL",
    asset: "SOL",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.72",
      reserveFactor: "0.2",
      supplyCap: "36000",
      borrowCap: "9000",
    },
    initialSupply: {
      amount: "21.2829576",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus lisUSD",
    symbol: "vlisUSD",
    asset: "lisUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      jumpMultiplierPerYear: "2.5",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0.1",
      supplyCap: "12000000",
      borrowCap: "10000000",
    },
    initialSupply: {
      amount: "1000000",
      vTokenReceiver: "0x1d60bBBEF79Fb9540D271Dbb01925380323A8f66",
    },
  },
  {
    name: "Venus PT-sUSDE-26JUN2025",
    symbol: "vPT-sUSDE-26JUN2025",
    asset: "PT-sUSDE-26JUN2025",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      jumpMultiplierPerYear: "2.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0.7",
      reserveFactor: "0",
      supplyCap: "2000000",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "10424.583228294074586275",
      vTokenReceiver: "0x63f6D9E7d3953106bCaf98832BD9C88A54AfCc9D",
    },
  },
  {
    name: "Venus sUSDe",
    symbol: "vsUSDe",
    asset: "sUSDe",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      jumpMultiplierPerYear: "2.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0",
      supplyCap: "2000000",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "4300",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus USDe",
    symbol: "vUSDe",
    asset: "USDe",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.075",
      jumpMultiplierPerYear: "0.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.25",
      supplyCap: "2000000",
      borrowCap: "1600000",
    },
    initialSupply: {
      amount: "5000",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus USD1",
    symbol: "vUSD1",
    asset: "USD1",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      jumpMultiplierPerYear: "2.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "0.25",
      supplyCap: "16000000",
      borrowCap: "14400000",
    },
    initialSupply: {
      amount: "4988.032727667459257279",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus xSolvBTC",
    symbol: "vxSolvBTC",
    asset: "xSolvBTC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      jumpMultiplierPerYear: "2",
      kink: "0.5",
    },
    riskParameters: {
      collateralFactor: "0.72",
      reserveFactor: "0.1",
      supplyCap: "100",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "1",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus asBNB",
    symbol: "vasBNB",
    asset: "asBNB",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      jumpMultiplierPerYear: "2",
      kink: "0.5",
    },
    riskParameters: {
      collateralFactor: "0.72",
      reserveFactor: "0.1",
      supplyCap: "2000",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "0.14",
      vTokenReceiver: "VTreasury",
    },
  },
] as const satisfies readonly Raw<VTokenConfig<"bscmainnet">>[];
