import { Raw, VTokenConfig } from "./types";

export default [
  {
    name: "Venus USDC",
    symbol: "vUSDC",
    asset: "USDC",
    interestRateModel: {
      model: "two-kinks",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      baseRatePerYear2: "0",
      multiplierPerYear2: "0.7",
      kink2: "0.9",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.81",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus USDT",
    symbol: "vUSDT",
    asset: "USDT",
    interestRateModel: {
      model: "two-kinks",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      baseRatePerYear2: "0",
      multiplierPerYear2: "0.7",
      kink2: "0.9",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus BUSD",
    symbol: "vBUSD",
    asset: "BUSD",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "1",
      supplyCap: "0",
      borrowCap: "0.000000000000000001",
    },
  },
  {
    name: "Venus SXP",
    symbol: "vSXP",
    asset: "SXP",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.5",
      reserveFactor: "0.1",
      supplyCap: "1007000000000000",
      borrowCap: "0",
    },
  },
  {
    name: "Venus BNB",
    symbol: "vBNB",
    asset: "BNB",
    interestRateModel: {
      model: "two-kinks",
      baseRatePerYear: "0",
      multiplierPerYear: "0.035",
      kink: "0.8",
      baseRatePerYear2: "0",
      multiplierPerYear2: "1.75",
      kink2: "0.9",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.3",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus XVS",
    symbol: "vXVS",
    asset: "XVS",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0",
      multiplierPerYear: "1",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.25",
      supplyCap: "3750000",
      borrowCap: "270000",
    },
  },
  {
    name: "Venus ETH",
    symbol: "vETH",
    asset: "ETH",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus LTC",
    symbol: "vLTC",
    asset: "LTC",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus XRP",
    symbol: "vXRP",
    asset: "XRP",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus BTC",
    symbol: "vBTC",
    asset: "BTCB",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus ADA",
    symbol: "vADA",
    asset: "ADA",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus DOGE",
    symbol: "vDOGE",
    asset: "DOGE",
    interestRateModel: {
      model: "whitepaper",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.1",
    },
    riskParameters: {
      collateralFactor: "0.8",
      reserveFactor: "0",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus CAKE",
    symbol: "vCAKE",
    asset: "CAKE",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.25",
      supplyCap: "uncapped",
      borrowCap: "50000",
    },
  },
  {
    name: "Venus MATIC",
    symbol: "vMATIC",
    asset: "MATIC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus AAVE",
    symbol: "vAAVE",
    asset: "AAVE",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus TUSDOLD",
    symbol: "vTUSDOLD",
    asset: "TUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.05",
      kink: "0.8",
      jumpMultiplierPerYear: "0.5",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "1",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus TRXOLD",
    symbol: "vTRXOLD",
    asset: "TRX",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.2",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus TRX",
    symbol: "vTRX",
    asset: "TRX",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.15",
      kink: "0.6",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.2",
      supplyCap: "uncapped",
      borrowCap: "0",
    },
  },
  {
    name: "Venus WBETH",
    symbol: "vWBETH",
    asset: "wBETH",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.75",
      jumpMultiplierPerYear: "2",
    },
    riskParameters: {
      collateralFactor: "0.5",
      reserveFactor: "0.2",
      supplyCap: "7601177882694808737457401254665533550748946046030666792960",
      borrowCap: "4000",
    },
  },
  {
    name: "Venus TUSD",
    symbol: "vTUSD",
    asset: "TUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      jumpMultiplierPerYear: "1.09",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "0.1",
      supplyCap: "1000000",
      borrowCap: "600000",
    },
  },
  {
    name: "Venus UNI",
    symbol: "vUNI",
    asset: "UNI",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0.25",
      supplyCap: "120000",
      borrowCap: "50000",
    },
  },
  {
    name: "Venus FDUSD",
    symbol: "vFDUSD",
    asset: "FDUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.10",
      kink: "0.8",
      jumpMultiplierPerYear: "2.5",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.1",
      supplyCap: "5500000",
      borrowCap: "4400000",
    },
    initialSupply: {
      amount: "9000",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus SolvBTC",
    symbol: "vSolvBTC",
    asset: "SolvBTC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      kink: "0.5",
      jumpMultiplierPerYear: "2",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.2",
      supplyCap: "100",
      borrowCap: "55",
    },
    initialSupply: {
      amount: "0.1572404",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus TWT",
    symbol: "vTWT",
    asset: "TWT",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.5",
      reserveFactor: "0.25",
      supplyCap: "2000000",
      borrowCap: "1000000",
    },
    initialSupply: {
      amount: "5000",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus THE",
    symbol: "vTHE",
    asset: "THE",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      kink: "0.45",
      jumpMultiplierPerYear: "3.5",
    },
    riskParameters: {
      collateralFactor: "0.53",
      reserveFactor: "0.25",
      supplyCap: "2400000",
      borrowCap: "1200000",
    },
    initialSupply: {
      amount: "12286",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus SOL",
    symbol: "vSOL",
    asset: "SOL",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0.02",
      multiplierPerYear: "0.2",
      kink: "0.5",
      jumpMultiplierPerYear: "3",
    },
    riskParameters: {
      collateralFactor: "0.72",
      reserveFactor: "0.2",
      supplyCap: "18000",
      borrowCap: "9000",
    },
    initialSupply: {
      amount: "20",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus lisUSD",
    symbol: "vlisUSD",
    asset: "lisUSD",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      kink: "0.8",
      jumpMultiplierPerYear: "2.5",
    },
    riskParameters: {
      collateralFactor: "0.55",
      reserveFactor: "0.1",
      supplyCap: "12000000",
      borrowCap: "10000000",
    },
    initialSupply: {
      amount: "1000000",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus PT-sUSDE-26JUN2025",
    symbol: "vPT-sUSDE-26JUN2025",
    asset: "PT-sUSDE-26JUN2025",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      jumpMultiplierPerYear: "2.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0.7",
      reserveFactor: "0",
      supplyCap: "2000000",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "10424.583228294074586275",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus sUSDe",
    symbol: "vsUSDe",
    asset: "sUSDe",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      jumpMultiplierPerYear: "2.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0",
      supplyCap: "2000000",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "4300",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus USDe",
    symbol: "vUSDe",
    asset: "USDe",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.075",
      jumpMultiplierPerYear: "0.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0.75",
      reserveFactor: "0.25",
      supplyCap: "2000000",
      borrowCap: "1600000",
    },
    initialSupply: {
      amount: "5000",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus USD1",
    symbol: "vUSD1",
    asset: "USD1",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.1",
      jumpMultiplierPerYear: "2.5",
      kink: "0.8",
    },
    riskParameters: {
      collateralFactor: "0",
      reserveFactor: "0.25",
      supplyCap: "16000000",
      borrowCap: "14400000",
    },
    initialSupply: {
      amount: "4988.032727667459257279",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus xSolvBTC",
    symbol: "vxSolvBTC",
    asset: "xSolvBTC",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      jumpMultiplierPerYear: "2",
      kink: "0.5",
    },
    riskParameters: {
      collateralFactor: "0.72",
      reserveFactor: "0.1",
      supplyCap: "100",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "1",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus asBNB",
    symbol: "vasBNB",
    asset: "asBNB",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      jumpMultiplierPerYear: "2",
      kink: "0.5",
    },
    riskParameters: {
      collateralFactor: "0.72",
      reserveFactor: "0.1",
      supplyCap: "2000",
      borrowCap: "0",
    },
    initialSupply: {
      amount: "0.14",
      vTokenReceiver: "VTreasury",
    },
  },
  {
    name: "Venus USDF",
    symbol: "vUSDF",
    asset: "USDF",
    interestRateModel: {
      model: "jump",
      baseRatePerYear: "0",
      multiplierPerYear: "0.09",
      jumpMultiplierPerYear: "2",
      kink: "0.5",
    },
    riskParameters: {
      collateralFactor: "0.6",
      reserveFactor: "0.1",
      supplyCap: "30000000",
      borrowCap: "27000000",
    },
    initialSupply: {
      amount: "100",
      vTokenReceiver: "VTreasury",
    },
  },
] as const satisfies readonly Raw<VTokenConfig<"bsctestnet">>[];
